name: myfood

services:
  webapi:
    container_name: myfood-webapi
    image: postech.myfood.webapi
    build:
      context: .
      dockerfile: src/PosTech.MyFood.WebApi/Dockerfile
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=https://+;http://+'
      - 'DOTNET_USE_POLLING_FILE_WATCHER=true'
      - 'ConnectionStrings:SQLConnection=${CONNECTION_STRINGS_SQL_CONNECTION}'
    networks:
      - myfood-network
    depends_on:
      - postgres

  postgres:
    container_name: myfood-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: myfooduser
      POSTGRES_PASSWORD: blueScreen@666
      POSTGRES_DB: myfooddb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myfood-network

volumes:
  postgres-data:

networks:
  myfood-network:
    driver: bridge